name: CI

on:
  push:    { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.10'
      - run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt playwright && playwright install
      - run: pytest --maxfail=1 --disable-warnings -q

      # only build & push if tests pass
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            kaw393939/601_module8:latest
            kaw393939/601_module8:${{ github.sha }}
