name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps & Playwright
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt playwright pytest-asyncio
          playwright install

      - name: Run tests & coverage
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov=main --cov-report=xml

  build:
    name: 🐳 Build & Push Docker Image
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # You can skip this if Docker is already available on macOS runner,
      # but adding buildx is harmless and gives you multi-arch support later.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # adjust these tags to your namespace
          tags: |
            ${ { secrets.DOCKERHUB_USERNAME } }/601_module8:latest
            ${ { secrets.DOCKERHUB_USERNAME } }/601_module8:${{ github.sha }}
